/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'total' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, bigint, string, bigint, string],
    Product
  >,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'initializeStore' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, bigint], Order>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, bigint, string],
    [] | [Product]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];